name: awzany
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.13.0-184.0.dev


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get_it: ^9.2.1
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.5.5
  cached_network_image_ce: ^4.7.0
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.8
  smooth_page_indicator: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/onboarding/

  # To add custom fonts to your application, add a fonts section here

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

